global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets:
          - 'traefik:8082'
  - job_name: 'data'
    static_configs:
      - targets:
          - 'data:8000'
