apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: e0618230-b9a4-471f-8633-d053edfb8c38
    editable: false