{
 "title": "My dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Open connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "traefik_entrypoint_open_connections",
     "legendFormat": "{{entrypoint}}, protocol: {{protocol}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Requests per Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "traefik_router_requests_total",
     "legendFormat": "{{protocol}} {{method}} request on service {{service}} via {{router}}: {{code}}"
    }
   ]
  },
  {
   "title": "Current active requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ktor_http_server_requests_active{instance=\"data:8000\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}