@startuml
'https://plantuml.com/class-diagram

class Route {
  +origin: String
  +route: String
  +destination: String
  +hours1: String
  +hours2: String
  +hours3: String
  +type: Char
  +area: String
  +altitude: String
  +aircraft: String
  +flow: String
  +seq: Int
  +d_artcc: String
  +a_artcc: String
}

@enduml